on: push

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CODECOV_TOKEN: 9dc807a6-ddb4-4974-a6b7-200f1e2d43b8
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          version-type: strict
          version-file: .tool-versions
      - name: Install deps
        run: mix deps.get
      - name: Check unused deps
        run: mix deps.unlock --check-unused
      - name: Run tests
        run: mix test
      - name: Run code test coverage report
        run: mix coveralls.json
      - name: Upload to Codecov
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov
